services:
  database:
    build: ./docker/database
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
    restart: always
  
  cache:
    image: redis:8.0.1-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    restart: always
