services:
  database:
    build: ./docker/database
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
      - ./docker/database/exchange:/opt/exchange
    restart: always
  
  cache:
    image: redis:8.0.1-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    restart: always

  analytics:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${ANALYTICS_POSTGRES_DB_URL}
      - DATABASE_TYPE=postgresql
      - APP_SECRET=${ANALYTICS_APP_SECRET}
      - REDIS_URL=redis://cache:6379
    depends_on:
      - database
    restart: always
